name       : kcodecs
version    : 5.106.0
release    : 69
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.106/kcodecs-5.106.0.tar.xz : f5dd4213e7747516a8785a0c0c3a59aac19bc797eac8c41c66833a7a26365ea3
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - MIT
component  : programming.library
summary    : String encoding library.
description: |
    String encoding library.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - gperf
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
