name       : kcodecs
version    : 5.94.0
release    : 63
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.94/kcodecs-5.94.0.tar.xz : bcc0e9fb1c1d259f05a326de160639a46c4bb6e0cce6fbc8244c39f251b8e7f9
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - MIT
component  : programming.library
summary    : String encoding library.
description: |
    String encoding library.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - gperf
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
