name       : kcodecs
version    : 5.84.0
release    : 54
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.84/kcodecs-5.84.0.tar.xz : 233f7123b045562c8ea7862eb40c27e551f6b463f9ed4fce4583433601f9523a
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - MIT
component  : programming.library
summary    : String encoding library.
description: |
    String encoding library.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - gperf
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
