name       : kcodecs
version    : 5.59.0
release    : 29
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.59/kcodecs-5.59.0.tar.xz : 768875bba3612a47419ac600107e045467feb55a4bf6ceb1cf51085c85c7a13a
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : String encoding library.
description: |
    String encoding library.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - gperf
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
