name       : kcodecs
version    : 5.77.0
release    : 46
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.77/kcodecs-5.77.0.tar.xz : c1b34aac21f6ab21e91e0e11f620949574678146f4407c853516c0f456e81fc4
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - MIT
component  : programming.library
optimize   : lto
summary    : String encoding library.
description: |
    String encoding library.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - gperf
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
