name       : kcodecs
version    : 5.105.0
release    : 68
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.105/kcodecs-5.105.0.tar.xz : c2e3c65d4fbac9fa3d47aa382764066ff875de0e3d8ff2bb87cf567f4e50e572
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - MIT
component  : programming.library
summary    : String encoding library.
description: |
    String encoding library.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - gperf
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
