name       : kcodecs
version    : 5.81.0
release    : 51
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.81/kcodecs-5.81.0.tar.xz : 4392afb4a3e1a4c8d6e645e7161d2651f5b83ca8620156cf942bfc95c33ce564
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - MIT
component  : programming.library
summary    : String encoding library.
description: |
    String encoding library.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - gperf
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
