name       : kcodecs
version    : 5.101.0
release    : 67
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.101/kcodecs-5.101.0.tar.xz : 9ebc28f2101cfafe544d6593f7d23b0438df2a77f8dc7d1f41afc1066846523a
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - MIT
component  : programming.library
summary    : String encoding library.
description: |
    String encoding library.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - gperf
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
