name       : kcodecs
version    : 5.107.0
release    : 70
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.107/kcodecs-5.107.0.tar.xz : 07b08563c0a4b29bbf08ea7a36c410d64936ab5e27cc772b8ca4f27a75a11221
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - MIT
component  : programming.library
summary    : String encoding library.
description: |
    String encoding library.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - gperf
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
