name       : kcodecs
version    : 5.56.0
release    : 26
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.56/kcodecs-5.56.0.tar.xz : e7234cddea70d4fa61dd66272dd43da401cc2543e40a6e9bb3a3655263419c82
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : String encoding library.
description: |
    String encoding library.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - gperf
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
