name       : kcodecs
version    : 5.57.0
release    : 27
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.57/kcodecs-5.57.0.tar.xz : c98b98cf7258c03fa5131a987e278f348d52f792dcb9f2a5664fe35aadea6995
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : String encoding library.
description: |
    String encoding library.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - gperf
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
