name       : kcodecs
version    : 5.64.0
release    : 34
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.64/kcodecs-5.64.0.tar.xz : 24cbffb123179cf4386500ae7bc7c99f65c4422cd7b91f314152f11cd596402a
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : String encoding library.
description: |
    String encoding library.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - gperf
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
