name       : kcodecs
version    : 5.67.0
release    : 37
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.67/kcodecs-5.67.0.tar.xz : 4fb9d2d2142306ff60b0855923be20a2a4d959075379c86c9af7023e20bdbab2
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : String encoding library.
description: |
    String encoding library.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - gperf
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
