name       : kcodecs
version    : 5.55.0
release    : 25
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.55/kcodecs-5.55.0.tar.xz : 4bd6fd48268d83b59f1b3c8ee19a50d9bee72f3601098dd5bb8e4b24a8912111
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : String encoding library.
description: |
    String encoding library.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - gperf
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
