name       : kcodecs
version    : 5.83.0
release    : 53
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.83/kcodecs-5.83.0.tar.xz : 02352cabd76a02c8c843b31d5ad8be208af7d17705cbcfca75733b5e3e518359
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - MIT
component  : programming.library
summary    : String encoding library.
description: |
    String encoding library.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - gperf
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
