name       : kcodecs
version    : 5.89.0
release    : 58
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.89/kcodecs-5.89.0.tar.xz : 3835e8dd48e27e7000f5a82c91f700c5d9783a4a55ef9ce1b7705314bdae57c8
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - MIT
component  : programming.library
summary    : String encoding library.
description: |
    String encoding library.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - gperf
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
