name       : kcodecs
version    : 5.25.0
release    : 1
source     :
    - http://download.kde.org/stable/frameworks/5.25/kcodecs-5.25.0.tar.xz : d5bef19f3575784e93b55db76bbaea7f8dba2bed4ffd9b9fbbb52db6d85f4ea5
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : String encoding library.
description: |
    String encoding library.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
