name       : kcodecs
version    : 5.52.0
release    : 22
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.52/kcodecs-5.52.0.tar.xz : 5b988a3a1d66e335e0a42addc0cb507b030db46e796e8d2355bbc122f09857fc
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : String encoding library.
description: |
    String encoding library.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - gperf
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
