name       : kcodecs
version    : 5.109.0
release    : 71
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.109/kcodecs-5.109.0.tar.xz : 9648fe05222c0755441a2091e4f97fd7b65649bcbaa2fb8c120e90d9c8934ca5
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - MIT
component  : programming.library
summary    : String encoding library.
description: |
    String encoding library.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - gperf
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
