name       : kcodecs
version    : 5.72.0
release    : 42
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.72/kcodecs-5.72.0.tar.xz : a125d9870e462cd6e1271385c10576e5e67661e0a0d7a7dece2effa684edc3b5
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : String encoding library.
description: |
    String encoding library.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - gperf
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
