name       : kcodecs
version    : 5.100.0
release    : 66
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.100/kcodecs-5.100.0.tar.xz : 55e8b79a27846d1ef90cdc2567b227b31ef8ef5325143c95d404f6eca1e40ca3
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - MIT
component  : programming.library
summary    : String encoding library.
description: |
    String encoding library.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - gperf
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
