name       : kcodecs
version    : 5.54.0
release    : 24
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.54/kcodecs-5.54.0.tar.xz : 4c4f59936999c824273b030ef4d0dc9faef5c3e26dbbbb1427232e7750f013e8
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : String encoding library.
description: |
    String encoding library.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - gperf
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
