name       : kcodecs
version    : 5.41.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.41/kcodecs-5.41.0.tar.xz : 0977b4eed346230837c3ec59e08e43977ae8657e18cc8e279f030199eeaa2679
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming
optimize   : lto
summary    : String encoding library.
description: |
    String encoding library.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - gperf
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
