name       : kcodecs
version    : 5.85.0
release    : 55
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.85/kcodecs-5.85.0.tar.xz : 65060af4bd3775aca56066f779ee4eeb34e05bf372023be2974302794e88f7fd
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - MIT
component  : programming.library
summary    : String encoding library.
description: |
    String encoding library.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - gperf
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
