name       : kcodecs
version    : 5.91.0
release    : 60
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.91/kcodecs-5.91.0.tar.xz : 3ec08377a1b2cbc30401ae9e43e1394c61635ab7537a37dc297cdc4deeda7c62
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - MIT
component  : programming.library
summary    : String encoding library.
description: |
    String encoding library.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - gperf
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
